#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class CheckBox;
                ref class ColorPicker;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace Hot3dxRotoDraw
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario6_ColorPicker : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario6_ColorPicker_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panel;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ alpha;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ m_frontColor;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ColorFrontRect;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ m_backColor;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ ColorBackRect;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ hexInput;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ alphaTextInput;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ alphaSlider;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ moreBtn;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ colorSlider;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ colorChannelInput;
        private: ::Windows::UI::Xaml::Controls::ColorPicker^ colorPicker;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ previewRect;
    };
}

