#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
                ref class TextBlock;
                ref class Button;
                ref class Slider;
                ref class ListBox;
                ref class Image;
                ref class ListBoxItem;
            }
        }
    }
}

namespace Hot3dxRotoDraw
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario5_MatsTexs : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario5_MatsTexs_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_PALETTE_FILE_NAME_EDIT;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath1TextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath2TextBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock2;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_CREATE_PALETTE_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_OPEN_PALETTE_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_ADD_MATERIAL_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SAVE_PALETTE_BUTTON2;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SET_MATERIAL_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_ADD_DELETEMATERIAL_BUTTON;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_NUM_MATERIALS_EDIT;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock2;
        private: ::Windows::UI::Xaml::Controls::Slider^ IDC_CURRENT_MATERIAL_slider1;
        private: ::Windows::UI::Xaml::Controls::Slider^ IDC_CURRENT_MATERIAL_slider2;
        private: ::Windows::UI::Xaml::Controls::Slider^ IDC_CURRENT_MATERIAL_slider3;
        private: ::Windows::UI::Xaml::Controls::Slider^ IDC_CURRENT_MATERIAL_slider4;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_CURRENT_MATERIAL_EDIT;
        private: ::Windows::UI::Xaml::Controls::ListBox^ MaterialListControl;
        private: ::Windows::UI::Xaml::Controls::ListBox^ MaterialListControlData;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock12;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_NAME_SET_BUTTON;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_NAME_SET_EDIT;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_TEXTURE_FILENAME_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_CLEAR_TEXTURE_FILENAME_BUTTON;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock13;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock14;
        private: ::Windows::UI::Xaml::Controls::Slider^ IDC_POWER_SLIDER;
        private: ::Windows::UI::Xaml::Controls::Button^ ID_COLOR_ADD_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Slider^ scrollBar;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureImage1;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_TEXTURE_IMAGE1_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_TEXTURE_IMAGE2_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureImage2;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ matName;
        private: ::Windows::UI::Xaml::Controls::ListBoxItem^ rgba_A;
    };
}

