#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class TextBlock;
                ref class TextBox;
                ref class Slider;
                ref class Button;
            }
        }
    }
}

namespace Hot3dxRotoDraw
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario4_MySettings : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario4_MySettings_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_DESCRIPTION4_STATIC;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_ALLSCALE_STATIC;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_ALLSCALE_EDIT;
        private: ::Windows::UI::Xaml::Controls::Slider^ AllScaleSlider;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_XSCALE_STATIC;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_XSCALE_EDIT;
        private: ::Windows::UI::Xaml::Controls::Slider^ XScaleSlider;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_YSCALE_STATIC;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_YSCALE_EDIT;
        private: ::Windows::UI::Xaml::Controls::Slider^ YScaleSlider;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_ZSCALE_STATIC;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_ZSCALE_EDIT;
        private: ::Windows::UI::Xaml::Controls::Slider^ ZScaleSlider;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_Settings_BUTTON1;
    };
}

