#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
                ref class TextBlock;
                ref class StackPanel;
                ref class SwapChainPanel;
                ref class Button;
                ref class Image;
                ref class CheckBox;
            }
        }
    }
}

namespace Hot3dxRotoDraw
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario5_Tex : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario5_Tex_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_PALETTE_FILE_NAME_EDIT;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileTextBlock6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFilePicTextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textureFileVideoTextBlock2;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ texPanel1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ texPanel2;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ texPanel3;
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel_Scenario5_Tex;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_D3DMATERIAL_DISPLAY;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_CREATE_PALETTE_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_OPEN_PALETTE_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SAVE_PALETTE_BUTTON2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ IDC_NAME_SET_EDIT;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_TEXTURE_FILENAME_BUTTON;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath1TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureImage1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath2TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureImage2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ImageTextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath3TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureRMAImage3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath4TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureEMMisiveImage4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ImageTextBlock2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath5TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureRadianceImage5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePath6TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ TextureIrradianceImage6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ImageTextBlock3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePathPic1TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ PicTextureImage2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ filePathVideo2TextBlock;
        private: ::Windows::UI::Xaml::Controls::Image^ VideoTextureImage2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ImageTextBlock4;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_PIC_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SHOW_BKGRND_BUTTON;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_GRID_OR_PIC_CHECKBOX;
    };
}

