#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace Hot3dxRotoDraw
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario3_FileIO : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario3_FileIO_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ panel1;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_New_BUTTON3;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_OPEN_BUTTON3;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SAVE_BUTTON3;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SAVEAS_BUTTON3;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SAVEALL_BUTTON3;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SAVE_TEXTURE_BUTTON3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_DESCRIPTION_STATIC;
    };
}

