//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "Scenario5_Tex.xaml.h"

void ::Hot3dxRotoDraw::Scenario5_Tex::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///Scenario5_Tex.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Hot3dxRotoDraw::Scenario5_Tex::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->IDC_PALETTE_FILE_NAME_EDIT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 4:
        {
            this->textBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 5:
        {
            this->textureFileTextBlock1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 6:
        {
            this->textureFileTextBlock2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 7:
        {
            this->textureFileTextBlock3 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 8:
        {
            this->textureFileTextBlock4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 9:
        {
            this->textureFileTextBlock5 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 10:
        {
            this->textureFileTextBlock6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 11:
        {
            this->textureFilePicTextBlock1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 12:
        {
            this->textureFileVideoTextBlock2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 13:
        {
            this->texPanel1 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 14:
        {
            this->texPanel2 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 15:
        {
            this->texPanel3 = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 16:
        {
            this->swapChainPanel_Scenario5_Tex = safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(__target);
        }
        break;
    case 17:
        {
            this->IDC_D3DMATERIAL_DISPLAY = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->IDC_D3DMATERIAL_DISPLAY))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::IDC_D3DMATERIAL_DISPLAY_SelectionChanged);
        }
        break;
    case 18:
        {
            this->IDC_CREATE_PALETTE_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 19:
        {
            this->IDC_OPEN_PALETTE_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 20:
        {
            this->IDC_SAVE_PALETTE_BUTTON2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 21:
        {
            this->IDC_NAME_SET_EDIT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 22:
        {
            this->IDC_TEXTURE_FILENAME_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 23:
        {
            this->filePath1TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePath1TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePath1TextBlock_SelectionChanged);
        }
        break;
    case 24:
        {
            this->TextureImage1 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureImage1))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::TextureImage1_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureImage1))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::TextureImage1_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureImage1))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::TextureImage1_RightTapped);
        }
        break;
    case 25:
        {
            this->filePath2TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePath2TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePath2TextBlock_SelectionChanged);
        }
        break;
    case 26:
        {
            this->TextureImage2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureImage2))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::TextureImage2_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureImage2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::TextureImage2_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureImage2))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::TextureImage2_RightTapped);
        }
        break;
    case 27:
        {
            this->ImageTextBlock1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 28:
        {
            this->filePath3TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePath3TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePath3TextBlock_SelectionChanged);
        }
        break;
    case 29:
        {
            this->TextureRMAImage3 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureRMAImage3))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::TextureImage3_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureRMAImage3))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::TextureRMAImage3_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureRMAImage3))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::TextureRMAImage3_RightTapped);
        }
        break;
    case 30:
        {
            this->filePath4TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePath4TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePath4TextBlock_SelectionChanged);
        }
        break;
    case 31:
        {
            this->TextureEMMisiveImage4 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureEMMisiveImage4))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::TextureImage4_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureEMMisiveImage4))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::TextureEMMisiveImage4_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureEMMisiveImage4))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::TextureNormalImage4_RightTapped);
        }
        break;
    case 32:
        {
            this->ImageTextBlock2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 33:
        {
            this->filePath5TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePath5TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePath5TextBlock_SelectionChanged);
        }
        break;
    case 34:
        {
            this->TextureRadianceImage5 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureRadianceImage5))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::TextureImage5_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureRadianceImage5))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::TextureRadianceImage5_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureRadianceImage5))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::TextureRadianceImage5_RightTapped);
        }
        break;
    case 35:
        {
            this->filePath6TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePath6TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePath6TextBlock_SelectionChanged);
        }
        break;
    case 36:
        {
            this->TextureIrradianceImage6 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureIrradianceImage6))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::TextureImage6_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureIrradianceImage6))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::TextureIrradianceImage6_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->TextureIrradianceImage6))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::TextureIrradianceImage6_RightTapped);
        }
        break;
    case 37:
        {
            this->ImageTextBlock3 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 38:
        {
            this->filePathPic1TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePathPic1TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePathPic1TextBlock_SelectionChanged);
        }
        break;
    case 39:
        {
            this->PicTextureImage2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PicTextureImage2))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::PicTextureImage2_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PicTextureImage2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::PicTextureImage2_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->PicTextureImage2))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::PicTextureImage2_RightTapped);
        }
        break;
    case 40:
        {
            this->filePathVideo2TextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(this->filePathVideo2TextBlock))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::filePathVideo2TextBlock_SelectionChanged);
        }
        break;
    case 41:
        {
            this->VideoTextureImage2 = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->VideoTextureImage2))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::VideoTextureImage2_Loaded);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->VideoTextureImage2))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&Scenario5_Tex::VideoTextureImage2_Tapped);
            (safe_cast<::Windows::UI::Xaml::Controls::Image^>(this->VideoTextureImage2))->RightTapped += ref new ::Windows::UI::Xaml::Input::RightTappedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::RightTappedRoutedEventArgs^))&Scenario5_Tex::VideoTextureImage2_RightTapped);
        }
        break;
    case 42:
        {
            this->ImageTextBlock4 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 43:
        {
            this->IDC_PIC_CHECKBOX = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->IDC_PIC_CHECKBOX))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::IDC_PIC_CHECKBOX_Checked);
        }
        break;
    case 44:
        {
            this->IDC_SHOW_BKGRND_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->IDC_SHOW_BKGRND_BUTTON))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::IDC_SHOW_BKGRND_BUTTON_Click);
        }
        break;
    case 45:
        {
            this->IDC_GRID_OR_PIC_CHECKBOX = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->IDC_GRID_OR_PIC_CHECKBOX))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_Tex::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&Scenario5_Tex::IDC_GRID_OR_PIC_CHECKBOX_Checked);
        }
        break;
    }
    _contentLoaded = true;
}

void ::Hot3dxRotoDraw::Scenario5_Tex::UnloadObject(::Windows::UI::Xaml::DependencyObject^ unloadableObject)
{
    if (unloadableObject != nullptr)
    {
        // Scenario5_Tex.xaml line 46
        if (unloadableObject == this->TextureImage1)
        {
            this->DisconnectUnloadedObject(24);
        }
        // Scenario5_Tex.xaml line 48
        if (unloadableObject == this->TextureImage2)
        {
            this->DisconnectUnloadedObject(26);
        }
        // Scenario5_Tex.xaml line 51
        if (unloadableObject == this->TextureRMAImage3)
        {
            this->DisconnectUnloadedObject(29);
        }
        // Scenario5_Tex.xaml line 53
        if (unloadableObject == this->TextureEMMisiveImage4)
        {
            this->DisconnectUnloadedObject(31);
        }
        // Scenario5_Tex.xaml line 56
        if (unloadableObject == this->TextureRadianceImage5)
        {
            this->DisconnectUnloadedObject(34);
        }
        // Scenario5_Tex.xaml line 58
        if (unloadableObject == this->TextureIrradianceImage6)
        {
            this->DisconnectUnloadedObject(36);
        }
        // Scenario5_Tex.xaml line 61
        if (unloadableObject == this->PicTextureImage2)
        {
            this->DisconnectUnloadedObject(39);
        }
        // Scenario5_Tex.xaml line 63
        if (unloadableObject == this->VideoTextureImage2)
        {
            this->DisconnectUnloadedObject(41);
        }
        ::Windows::UI::Xaml::Markup::XamlMarkupHelper::UnloadObject(unloadableObject);
    }
}

void ::Hot3dxRotoDraw::Scenario5_Tex::DisconnectUnloadedObject(int connectionId)
{
    switch(connectionId)
    {
        case 24: // Scenario5_Tex.xaml line 46
        {
            this->TextureImage1 = nullptr;
            break;
        }
        case 26: // Scenario5_Tex.xaml line 48
        {
            this->TextureImage2 = nullptr;
            break;
        }
        case 29: // Scenario5_Tex.xaml line 51
        {
            this->TextureRMAImage3 = nullptr;
            break;
        }
        case 31: // Scenario5_Tex.xaml line 53
        {
            this->TextureEMMisiveImage4 = nullptr;
            break;
        }
        case 34: // Scenario5_Tex.xaml line 56
        {
            this->TextureRadianceImage5 = nullptr;
            break;
        }
        case 36: // Scenario5_Tex.xaml line 58
        {
            this->TextureIrradianceImage6 = nullptr;
            break;
        }
        case 39: // Scenario5_Tex.xaml line 61
        {
            this->PicTextureImage2 = nullptr;
            break;
        }
        case 41: // Scenario5_Tex.xaml line 63
        {
            this->VideoTextureImage2 = nullptr;
            break;
        }
        default:
        {
            throw ref new ::Platform::InvalidArgumentException("Invalid connectionId.");
        }
    }
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Hot3dxRotoDraw::Scenario5_Tex::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


