#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class TextBlock;
                ref class TextBox;
                ref class Image;
                ref class CheckBox;
                ref class Button;
            }
        }
    }
}

namespace Hot3dxRotoDraw
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Scenario11_GridorPic : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class Scenario11_GridorPic_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ HeaderPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ IDC_DESCRIPTION_STATIC;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ m_gridorPicText;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_gridorPicTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ m_gridorPicFilesText;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_gridorPicFilesTextBox;
        private: ::Windows::UI::Xaml::Controls::Image^ PicTextureImage1;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_GRID_OR_PIC_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_PIC_TEXTURE_IMAGE1_BUTTON;
        private: ::Windows::UI::Xaml::Controls::Button^ IDC_SHOW_BACKGROUND_PIC_BUTTON;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_PIC_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_SCREENGRAB_DDS_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_SCREENGRAB_BMP_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_SCREENGRAB_PNG_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_SCREENGRAB_JPG_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_SCREENGRAB_TIFF_CHECKBOX;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ IDC_SCREENGRAB_GIF_CHECKBOX;
    };
}

