//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "Scenario5_MatsTexs.xaml.h"

void ::Hot3dxRotoDraw::Scenario5_MatsTexs::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///Scenario5_MatsTexs.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Hot3dxRotoDraw::Scenario5_MatsTexs::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->IDC_PALETTE_FILE_NAME_EDIT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 4:
        {
            this->textBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 5:
        {
            this->IDC_CREATE_PALETTE_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 6:
        {
            this->IDC_OPEN_PALETTE_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 7:
        {
            this->IDC_ADD_MATERIAL_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 8:
        {
            this->IDC_SAVE_PALETTE_BUTTON2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 9:
        {
            this->IDC_SET_MATERIAL_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 10:
        {
            this->IDC_ADD_DELETEMATERIAL_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 11:
        {
            this->textBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 12:
        {
            this->IDC_NUM_MATERIALS_EDIT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 13:
        {
            this->textBlock2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 14:
        {
            this->IDC_CURRENT_MATERIAL_slider1 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 15:
        {
            this->IDC_CURRENT_MATERIAL_slider2 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 16:
        {
            this->IDC_CURRENT_MATERIAL_slider3 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 17:
        {
            this->IDC_CURRENT_MATERIAL_slider4 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 18:
        {
            this->IDC_CURRENT_MATERIAL_EDIT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 19:
        {
            this->MaterialListControl = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(this->MaterialListControl))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_MatsTexs::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&Scenario5_MatsTexs::MaterialListControl_SelectionChanged);
        }
        break;
    case 20:
        {
            this->MaterialListControlData = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(this->MaterialListControlData))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Hot3dxRotoDraw::Scenario5_MatsTexs::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&Scenario5_MatsTexs::MaterialListControlData_SelectionChanged);
        }
        break;
    case 21:
        {
            this->textBlock12 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 22:
        {
            this->IDC_NAME_SET_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 23:
        {
            this->IDC_NAME_SET_EDIT = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 24:
        {
            this->IDC_TEXTURE_FILENAME_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 25:
        {
            this->IDC_CLEAR_TEXTURE_FILENAME_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 26:
        {
            this->textBlock13 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 27:
        {
            this->textBlock14 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 28:
        {
            this->IDC_POWER_SLIDER = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 29:
        {
            this->IDC_OTHERS_SLIDER = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 30:
        {
            this->IDC_D3DMATERIAL_DISPLAY = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 31:
        {
            this->ID_COLOR_ADD_BUTTON = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 32:
        {
            this->scrollBar = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
        }
        break;
    case 33:
        {
            this->v0 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 34:
        {
            this->v1 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 35:
        {
            this->v2 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 36:
        {
            this->v3 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 37:
        {
            this->v4 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 38:
        {
            this->v5 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 39:
        {
            this->v6 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 40:
        {
            this->v7 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 41:
        {
            this->v8 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 42:
        {
            this->v9 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 43:
        {
            this->v10 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 44:
        {
            this->v11 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 45:
        {
            this->v12 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 46:
        {
            this->v13 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 47:
        {
            this->v15 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 48:
        {
            this->v16 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 49:
        {
            this->v17 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 50:
        {
            this->v18 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 51:
        {
            this->v19 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 52:
        {
            this->matName = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 53:
        {
            this->rgba_A = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 54:
        {
            this->rgba_R = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 55:
        {
            this->rgba_G = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 56:
        {
            this->rgba_B = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 57:
        {
            this->Alpha = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 58:
        {
            this->Power = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 59:
        {
            this->SP_R = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 60:
        {
            this->SP_G = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 61:
        {
            this->SP_B = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 62:
        {
            this->AMB_R = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 63:
        {
            this->AMB_G = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 64:
        {
            this->AMB_B = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 65:
        {
            this->EMM_R = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 66:
        {
            this->EMM_G = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 67:
        {
            this->EMM_B = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 68:
        {
            this->DIF_R = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 69:
        {
            this->DIF_G = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    case 70:
        {
            this->DIF_B = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Hot3dxRotoDraw::Scenario5_MatsTexs::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


