//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "App.xaml.h"
#include "DirectXPage.xaml.h"
#include "Scenario10_Sculpt.xaml.h"
#include "Scenario11_GridorPic.xaml.h"
#include "Scenario1_Start.xaml.h"
#include "Scenario2_Normal.xaml.h"
#include "Scenario3_FileIO.xaml.h"
#include "Scenario4_MySettings.xaml.h"
#include "Scenario5_MatsTexs.xaml.h"
#include "Scenario6_ColorPicker.xaml.h"
#include "Scenario7_SphereDraw.xaml.h"
#include "Scenario8_Help.xaml.h"
#include "Scenario9_Rotate.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "App.g.hpp"
#include "DirectXPage.g.hpp"
#include "Scenario10_Sculpt.g.hpp"
#include "Scenario11_GridorPic.g.hpp"
#include "Scenario1_Start.g.hpp"
#include "Scenario2_Normal.g.hpp"
#include "Scenario3_FileIO.g.hpp"
#include "Scenario4_MySettings.g.hpp"
#include "Scenario5_MatsTexs.g.hpp"
#include "Scenario6_ColorPicker.g.hpp"
#include "Scenario7_SphereDraw.g.hpp"
#include "Scenario8_Help.g.hpp"
#include "Scenario9_Rotate.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_Version(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->Version);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_UseCompactResources(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->UseCompactResources);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_ControlsResourcesVersion(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->ControlsResourcesVersion);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_IsExpanded(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->IsExpanded);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_HasUnrealizedChildren(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->HasUnrealizedChildren);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_Depth(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->Depth);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_HasChildren(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->HasChildren);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Content(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Content;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Children(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Children;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_Parent(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->Parent;
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_Version(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Version = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetEnumMember_ControlsResourcesVersion(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->ControlsResourcesVersion = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_UseCompactResources(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->UseCompactResources = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_IsExpanded(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->IsExpanded = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_HasUnrealizedChildren(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->HasUnrealizedChildren = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_Content(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->Content = safe_cast<TValue^>(value);
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    unsigned int flags;
    int boxedTypeIndex;
};

const TypeInfo TypeInfos[] = 
{
    //   0
    L"Int32", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   1
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   2
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   3
    L"System.Enum", L"",
    nullptr, nullptr, nullptr, nullptr,
    4, // System.ValueType
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //   4
    L"System.ValueType", L"",
    nullptr, nullptr, nullptr, nullptr,
    1, // Object
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //   5
    L"Hot3dxRotoDraw.DirectXPage", L"",
    &ActivateType<::Hot3dxRotoDraw::DirectXPage>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //   6
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //   7
    L"Hot3dxRotoDraw.Scenario8_Help", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario8_Help>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //   8
    L"Hot3dxRotoDraw.Scenario1_Start", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario1_Start>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //   9
    L"Hot3dxRotoDraw.Scenario2_Normal", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario2_Normal>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  10
    L"Hot3dxRotoDraw.Scenario3_FileIO", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario3_FileIO>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  11
    L"Hot3dxRotoDraw.Scenario9_Rotate", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario9_Rotate>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  12
    L"Hot3dxRotoDraw.Scenario10_Sculpt", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario10_Sculpt>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  13
    L"Windows.UI.Xaml.DependencyObject", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  14
    L"Hot3dxRotoDraw.Scenario5_MatsTexs", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario5_MatsTexs>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  15
    L"Windows.UI.Xaml.ResourceDictionary", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  16
    L"Hot3dxRotoDraw.Scenario11_GridorPic", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario11_GridorPic>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  17
    L"Hot3dxRotoDraw.Scenario4_MySettings", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario4_MySettings>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  18
    L"Hot3dxRotoDraw.Scenario7_SphereDraw", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario7_SphereDraw>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  19
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    -1,
    //  20
    L"Hot3dxRotoDraw.Scenario6_ColorPicker", L"",
    &ActivateType<::Hot3dxRotoDraw::Scenario6_ColorPicker>, nullptr, nullptr, nullptr,
    6, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    -1,
    //  21
    L"Microsoft.UI.Xaml.Controls.TreeViewNode", L"",
    &ActivateType<::Microsoft::UI::Xaml::Controls::TreeViewNode>, nullptr, nullptr, nullptr,
    13, // Windows.UI.Xaml.DependencyObject
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsBindable | TypeInfo_Flags_None,
    -1,
    //  22
    L"Microsoft.UI.Xaml.Controls.StylesVersion", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::Microsoft::UI::Xaml::Controls::StylesVersion>,
    3, // System.Enum
    7, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  23
    L"Microsoft.UI.Xaml.Controls.XamlControlsResources", L"",
    &ActivateType<::Microsoft::UI::Xaml::Controls::XamlControlsResources>, nullptr, &DictionaryAdd<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Platform::Object^, ::Platform::Object^>, nullptr,
    15, // Windows.UI.Xaml.ResourceDictionary
    7, 2, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  24
    L"Microsoft.UI.Xaml.Controls.ControlsResourcesVersion", L"",
    nullptr, nullptr, nullptr, &FromStringConverter<::Microsoft::UI::Xaml::Controls::ControlsResourcesVersion>,
    3, // System.Enum
    10, 2, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_None,
    -1,
    //  25
    L"Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.TreeViewNode>", L"",
    nullptr, &CollectionAdd<::Windows::Foundation::Collections::IVector<::Microsoft::UI::Xaml::Controls::TreeViewNode^>, ::Microsoft::UI::Xaml::Controls::TreeViewNode^>, nullptr, nullptr,
    -1,
    10, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    -1,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    10, 4, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_None,
};

const UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      1,   //   6
      2,   //   7
      3,   //   8
      3,   //   9
      3,   //  10
      3,   //  11
      4,   //  12
      4,   //  13
      4,   //  14
      4,   //  15
      4,   //  16
      5,   //  17
      5,   //  18
      5,   //  19
      5,   //  20
      5,   //  21
      5,   //  22
      5,   //  23
      5,   //  24
      5,   //  25
      5,   //  26
      6,   //  27
      6,   //  28
      6,   //  29
      8,   //  30
      9,   //  31
     12,   //  32
     14,   //  33
     15,   //  34
     16,   //  35
     19,   //  36
     21,   //  37
     21,   //  38
     21,   //  39
     22,   //  40
     23,   //  41
     23,   //  42
     23,   //  43
     23,   //  44
     23,   //  45
     23,   //  46
     23,   //  47
     23,   //  48
     24,   //  49
     24,   //  50
     24,   //  51
     25,   //  52
     25,   //  53
     25,   //  54
     25,   //  55
     25,   //  56
     25,   //  57
     25,   //  58
     25,   //  59
     25,   //  60
     25,   //  61
     25,   //  62
     25,   //  63
     25,   //  64
     25,   //  65
     25,   //  66
     25,   //  67
     25,   //  68
     25,   //  69
     25,   //  70
     25,   //  71
     25,   //  72
     25,   //  73
     25,   //  74
     25,   //  75
     25,   //  76
     25,   //  77
     25,   //  78
     25,   //  79
     25,   //  80
     25,   //  81
     26,   //  82
};

const TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    auto typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

struct EnumValueInfo
{
    PCWSTR name;
    int eValue;
};

const EnumValueInfo EnumValues[] =
{ 
    L"Latest", (int) ::Microsoft::UI::Xaml::Controls::StylesVersion::Latest,
    L"WinUI_2dot5", (int) ::Microsoft::UI::Xaml::Controls::StylesVersion::WinUI_2dot5,
    L"Version1", (int) ::Microsoft::UI::Xaml::Controls::ControlsResourcesVersion::Version1,
    L"Version2", (int) ::Microsoft::UI::Xaml::Controls::ControlsResourcesVersion::Version2,
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - Microsoft.UI.Xaml.Controls.TreeViewNode.IsExpanded
    L"IsExpanded",
    &GetValueTypeMember_IsExpanded<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::Platform::Boolean>,
    &SetValueTypeMember_IsExpanded<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, true,  false,
    //   1 - Microsoft.UI.Xaml.Controls.TreeViewNode.HasUnrealizedChildren
    L"HasUnrealizedChildren",
    &GetValueTypeMember_HasUnrealizedChildren<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::Platform::Boolean>,
    &SetValueTypeMember_HasUnrealizedChildren<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, false, false,
    //   2 - Microsoft.UI.Xaml.Controls.TreeViewNode.Content
    L"Content",
    &GetReferenceTypeMember_Content<::Microsoft::UI::Xaml::Controls::TreeViewNode>,
    &SetReferenceTypeMember_Content<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::Platform::Object>,
    1, // Object
    -1,
    false, true,  false,
    //   3 - Microsoft.UI.Xaml.Controls.TreeViewNode.Children
    L"Children",
    &GetReferenceTypeMember_Children<::Microsoft::UI::Xaml::Controls::TreeViewNode>,
    nullptr,
    25, // Windows.Foundation.Collections.IVector`1<Microsoft.UI.Xaml.Controls.TreeViewNode>
    -1,
    true,  false, false,
    //   4 - Microsoft.UI.Xaml.Controls.TreeViewNode.Depth
    L"Depth",
    &GetValueTypeMember_Depth<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::default::int32>,
    nullptr,
    0, // Int32
    -1,
    true,  true,  false,
    //   5 - Microsoft.UI.Xaml.Controls.TreeViewNode.HasChildren
    L"HasChildren",
    &GetValueTypeMember_HasChildren<::Microsoft::UI::Xaml::Controls::TreeViewNode, ::Platform::Boolean>,
    nullptr,
    2, // Boolean
    -1,
    true,  true,  false,
    //   6 - Microsoft.UI.Xaml.Controls.TreeViewNode.Parent
    L"Parent",
    &GetReferenceTypeMember_Parent<::Microsoft::UI::Xaml::Controls::TreeViewNode>,
    nullptr,
    21, // Microsoft.UI.Xaml.Controls.TreeViewNode
    -1,
    true,  false, false,
    //   7 - Microsoft.UI.Xaml.Controls.XamlControlsResources.Version
    L"Version",
    &GetValueTypeMember_Version<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Microsoft::UI::Xaml::Controls::StylesVersion>,
    &SetEnumMember_Version<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Microsoft::UI::Xaml::Controls::StylesVersion>,
    22, // Microsoft.UI.Xaml.Controls.StylesVersion
    -1,
    false, true,  false,
    //   8 - Microsoft.UI.Xaml.Controls.XamlControlsResources.UseCompactResources
    L"UseCompactResources",
    &GetValueTypeMember_UseCompactResources<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Platform::Boolean>,
    &SetValueTypeMember_UseCompactResources<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, true,  false,
    //   9 - Microsoft.UI.Xaml.Controls.XamlControlsResources.ControlsResourcesVersion
    L"ControlsResourcesVersion",
    &GetValueTypeMember_ControlsResourcesVersion<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Microsoft::UI::Xaml::Controls::ControlsResourcesVersion>,
    &SetEnumMember_ControlsResourcesVersion<::Microsoft::UI::Xaml::Controls::XamlControlsResources, ::Microsoft::UI::Xaml::Controls::ControlsResourcesVersion>,
    24, // Microsoft.UI.Xaml.Controls.ControlsResourcesVersion
    -1,
    false, true,  false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}


const MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    auto lastDotIndex = longMemberName->Length();
    while (true)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
        if (lastDotIndex == 0)
        {
            break;
        }
        lastDotIndex--;
    }
    return nullptr;
}

#pragma warning(push)
#pragma warning(disable: 4691)
::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        ::Windows::UI::Xaml::Markup::IXamlMetadataProvider^ provider;
        provider = ref new ::Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider();
        otherProviders->Append(provider); 
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}
#pragma warning(pop)

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;
        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;
        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;
        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;
        userType->CreateFromStringMethod = nullptr;
        userType->SetBoxedType(this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->boxedTypeIndex >= 0 ? TypeInfos[pTypeInfo->boxedTypeIndex].typeName : L"")));
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        for (int i = pTypeInfo->firstEnumValueIndex; i < pNextTypeInfo->firstEnumValueIndex; i++)
        {
            userType->AddEnumValue(
                ::Platform::StringReference(EnumValues[i].name),
                ::Windows::Foundation::PropertyValue::CreateInt32(EnumValues[i].eValue));
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

