//--------------------------------------------------------------------------------------
// File: Hot3dxRotoDrawMain.h
//
// Copyright (c) 2020 Jeff Kubitz - hot3dx. All rights reserved.
// And by CoPilot AI - OpenAI
// No warranty is expressed or implied use at own risk
//
//--------------------------------------------------------------------------------------#pragma once

#include "pch.h"
#include "WavefrontObjFileWriter.h"
#include <sstream>

using namespace Hot3dxRotoDraw;

WavefrontObjFileWriter::WavefrontObjFileWriter(const std::string& filename)
    : m_filename(filename)
{
}

WavefrontObjFileWriter::~WavefrontObjFileWriter()
{
}

void WavefrontObjFileWriter::WriteObjFile(std::ofstream& outFile)
{
    // Write file header or comments
    outFile << "# Wavefront OBJ file\n";
    outFile << "# Generated by WavefrontObjFileWriter\n\n";
    // Add your OBJ writing logic here
}

std::string WavefrontObjFileWriter::WriteVertex(float x, float y, float z)
{
    std::ostringstream oss;
    oss << "v " << x << " " << y << " " << z << "\n";
    return oss.str();
}

std::string WavefrontObjFileWriter::WriteNormal(float nx, float ny, float nz)
{
    std::ostringstream oss;
    oss << "vn " << nx << " " << ny << " " << nz << "\n";
    return oss.str();
}

std::string WavefrontObjFileWriter::WriteTexCoord(float u, float v)
{
    std::ostringstream oss;
    oss << "vt " << u << " " << v << "\n";
    return oss.str();
}

std::string WavefrontObjFileWriter::WriteFace(const std::vector<int>& vertexIndices)
{
    std::ostringstream oss;
    oss << "f";
    for (int idx : vertexIndices)
    {
        oss << " " << idx;
    }
    oss << "\n";
    return oss.str();
}